### ISSUE TITLE
Ondřej's name renders as ONDřEJ ČERTÍK

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-paper#96]
This might just be a bug with the SIAM template, which converts the author names to uppercase. If you use `On\v{r}ej` it gives `ONDŘEJ` correctly. But right now it's using the Unicode characters and the `Ř` is kept lowercase. 

@certik

**Comment by certik** [comment]
I noticed that. It's rendering lowercase ř instead of the uppercase Ř.
Typically that's a sign that the language support, that has these lower
case/upper case mappings, is not loaded properly. It knows about í, but not
ř. Č was already uppercase. The \v{r} is only a partial solution, as that
sometimes can position the accent above the letter incorrectly -- the
accented letter must be in the font itself.

For now, we can add this latex representation into the json, as you
suggested. Not ideal, but allows us to move on. In the end, it's the
journal's job to get the fonts right.

**Comment by asmeurer** [comment]
I would bring it up with the journal once we submit. I just wanted to make sure we are aware of the issue.

**Comment by certik** [comment]
The solution is to use `\MakeUppercase` instead of `\uppercase`, see http://tex.stackexchange.com/questions/289465/stylesheet-does-not-capitalize-polish-letters-correctly. That's a bug in the journal template.
